import 'package:cloud_firestore/cloud_firestore.dart';

import '../../domain/entities/group.dart';

/// Firestore data model for the "groups" collection.
///
/// Handles serialization/deserialization between [Group] domain entities
/// and Firestore `Map<String, dynamic>` documents.
///
/// Collection name: `groups`
/// Document ID:     auto-generated by Firestore
///
/// The document shape matches the deployed security rules:
/// - `created_by`   : String   — uid of the creator.
/// - `member_ids`   : String[] — uids of every member (for rules + queries).
/// - `group_admin`  : Map      — the admin's full profile snapshot.
/// - `members`      : List<Map>— full member profile snapshots for display.
class GroupModel {
  const GroupModel._({
    required this.id,
    required this.groupName,
    required this.createdAt,
    required this.updatedAt,
    required this.createdBy,
    required this.memberIds,
    required this.groupAdmin,
    required this.members,
    required this.memberCount,
    this.groupPicture,
  });

  /// Firestore collection path.
  static const String collectionName = 'groups';

  final String id;
  final String groupName;
  final String? groupPicture;
  final DateTime createdAt;
  final DateTime updatedAt;
  final String createdBy;
  final List<String> memberIds;
  final Map<String, dynamic> groupAdmin;
  final List<Map<String, dynamic>> members;
  final int memberCount;

  /// Creates a [GroupModel] from a Firestore document.
  factory GroupModel.fromDocument(
      DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data() ?? <String, dynamic>{};

    return GroupModel._(
      id: doc.id,
      groupName: data['group_name'] as String? ?? '',
      groupPicture: data['group_picture'] as String?,
      createdAt:
          (data['created_at'] as Timestamp?)?.toDate() ?? DateTime.now(),
      updatedAt:
          (data['updated_at'] as Timestamp?)?.toDate() ?? DateTime.now(),
      createdBy: data['created_by'] as String? ?? '',
      memberIds: _normalizeStringList(data['member_ids']),
      groupAdmin: _normalizeMemberMap(data['group_admin']),
      members: _normalizeMemberList(data['members']),
      memberCount: (data['member_count'] as num?)?.toInt() ?? 0,
    );
  }

  /// Creates a [GroupModel] from a plain map (useful for testing).
  factory GroupModel.fromMap(Map<String, dynamic> map,
      {required String id}) {
    return GroupModel._(
      id: id,
      groupName: map['group_name'] as String? ?? '',
      groupPicture: map['group_picture'] as String?,
      createdAt:
          (map['created_at'] as Timestamp?)?.toDate() ?? DateTime.now(),
      updatedAt:
          (map['updated_at'] as Timestamp?)?.toDate() ?? DateTime.now(),
      createdBy: map['created_by'] as String? ?? '',
      memberIds: _normalizeStringList(map['member_ids']),
      groupAdmin: _normalizeMemberMap(map['group_admin']),
      members: _normalizeMemberList(map['members']),
      memberCount: (map['member_count'] as num?)?.toInt() ?? 0,
    );
  }

  /// Serializes to a Firestore-compatible map.
  ///
  /// Timestamps are stored as [FieldValue.serverTimestamp] when the value
  /// is `null` (i.e. on create), so the server sets them consistently.
  Map<String, dynamic> toMap({bool isNew = false}) {
    return {
      'group_name': groupName,
      'group_picture': groupPicture,
      'created_at': isNew ? FieldValue.serverTimestamp() : createdAt,
      'updated_at': FieldValue.serverTimestamp(),
      'created_by': createdBy,
      'member_ids': memberIds,
      'group_admin': groupAdmin,
      'members': members,
      'member_count': memberCount,
    };
  }

  /// Converts to the domain entity.
  Group toEntity() {
    return Group(
      id: id,
      groupName: groupName,
      groupPicture: groupPicture,
      createdAt: createdAt,
      updatedAt: updatedAt,
      createdBy: createdBy,
      memberIds: List<String>.of(memberIds),
      groupAdmin: _toGroupMember(groupAdmin),
      members: members.map(_toGroupMember).toList(),
      memberCount: memberCount,
    );
  }

  /// Creates a [GroupModel] from a [Group] entity.
  static GroupModel fromEntity(Group group) {
    return GroupModel._(
      id: group.id,
      groupName: group.groupName,
      groupPicture: group.groupPicture,
      createdAt: group.createdAt,
      updatedAt: group.updatedAt,
      createdBy: group.createdBy,
      memberIds: List<String>.of(group.memberIds),
      groupAdmin: _fromGroupMember(group.groupAdmin),
      members: group.members.map(_fromGroupMember).toList(),
      memberCount: group.memberCount,
    );
  }

  // ─────────────────────────────────────────────────────────────────────
  // Helpers
  // ─────────────────────────────────────────────────────────────────────

  /// Coerces a Firestore value into a list of strings.
  static List<String> _normalizeStringList(dynamic value) {
    if (value is! List) return [];
    return value.whereType<String>().toList(growable: false);
  }

  /// Coerces a Firestore value into a single member map. Returns an empty
  /// map when the value is missing or not a map (e.g. legacy documents).
  static Map<String, dynamic> _normalizeMemberMap(dynamic value) {
    if (value is! Map<String, dynamic>) return <String, dynamic>{};
    return value;
  }

  /// Coerces a Firestore value into a list of member maps.
  static List<Map<String, dynamic>> _normalizeMemberList(dynamic value) {
    if (value is! List) return [];
    return value
        .whereType<Map<String, dynamic>>()
        .toList(growable: false);
  }

  /// Converts a stored member map into a [GroupMember] entity.
  static GroupMember _toGroupMember(Map<String, dynamic> map) {
    return GroupMember(
      id: map['id'] as String? ?? '',
      fullName: map['full_name'] as String? ?? '',
      email: map['email'] as String? ?? '',
      phoneNumber: map['phone_number'] as String?,
      displayName: map['display_name'] as String?,
      profilePicture: map['profile_picture'] as String?,
      role: (map['role'] as String?) == 'admin'
          ? MemberRole.admin
          : MemberRole.member,
    );
  }

  /// Converts a [GroupMember] entity into a storable member map.
  static Map<String, dynamic> _fromGroupMember(GroupMember member) {
    return {
      'id': member.id,
      'full_name': member.fullName,
      'email': member.email,
      'phone_number': member.phoneNumber,
      'display_name': member.displayName,
      'profile_picture': member.profilePicture,
      'role': member.role == MemberRole.admin ? 'admin' : 'member',
    };
  }
}
