import '../../domain/entities/bill.dart';

/// Abstract repository for the "bills" Firestore subcollection.
///
/// Every bill lives under `groups/{groupId}/bills/{billId}`. This repository
/// encapsulates all CRUD operations against that subcollection so the
/// presentation layer never touches Firestore directly.
abstract class BillRepository {
  /// Creates a new bill document under `groups/{groupId}/bills`.
  ///
  /// A new document ID is auto-generated by Firestore. The created [Bill]
  /// (with the assigned document ID and server-set timestamps) is returned.
  Future<Bill> createBill(Bill bill);

  /// Fetches a single bill by its [billId] within the given [groupId].
  ///
  /// Returns `null` if the document does not exist.
  Future<Bill?> getBill(String groupId, String billId);

  /// Fetches all bills for the given [groupId], ordered by `created_at`
  /// descending (newest first).
  Future<List<Bill>> getBillsForGroup(String groupId);

  /// Streams all bills for the given [groupId] in real time.
  ///
  /// Emits a new list whenever any bill in the subcollection is added,
  /// modified, or removed. Ordered by `created_at` descending.
  Stream<List<Bill>> watchBillsForGroup(String groupId);

  /// Updates an existing bill document.
  ///
  /// The `updated_at` timestamp is always refreshed.
  Future<void> updateBill(Bill bill);

  /// Updates the payment status of a bill.
  Future<void> updatePaymentStatus(
    String groupId,
    String billId,
    BillPaymentStatus status,
  );

  /// Streams a single bill document in real time.
  ///
  /// Emits a new [Bill] whenever the bill document changes (e.g. when a
  /// participant submits a payment request or the creator verifies one).
  /// Returns `null` if the document does not exist.
  Stream<Bill?> watchBill(String groupId, String billId);

  /// Submits a payment request on behalf of [memberId].
  ///
  /// [requestType] indicates whether the participant claims to have paid in
  /// full ([PaymentRequestType.paid]) or partially
  /// ([PaymentRequestType.partially]). [requestedAmount] is the amount the
  /// participant claims to have paid — for a full payment it should equal
  /// their share, for a partial payment it must be less than their share.
  ///
  /// Sets the participant's [ParticipantPaymentStatus] to `requested` and
  /// records the request timestamp. The bill creator must verify the
  /// request via [verifyParticipantPayment] before the participant's status
  /// becomes `paid` or `partially_paid`.
  Future<void> requestParticipantPayment({
    required String groupId,
    required String billId,
    required String memberId,
    required PaymentRequestType requestType,
    required double requestedAmount,
  });

  /// Verifies (approves or rejects) a participant's payment request.
  ///
  /// Only the bill creator should call this. When [approved] is `true`,
  /// [receivedAmount] is the amount the creator confirms they actually
  /// received. The participant's status becomes `paid` when the received
  /// amount equals (or exceeds) their share, otherwise `partially_paid`.
  /// When [approved] is `false`, the participant's status becomes
  /// `rejected` and they may submit a new request.
  ///
  /// The bill-level [BillPaymentStatus] is recomputed from all
  /// participants' states after the update.
  Future<void> verifyParticipantPayment({
    required String groupId,
    required String billId,
    required String memberId,
    required bool approved,
    required double receivedAmount,
    required String verifiedBy,
  });

  /// Deletes a bill document.
  Future<void> deleteBill(String groupId, String billId);
}
